--Create Cacophony metadata database
CREATE DATABASE cacophony_metadata;

CREATE USER USERNAME PASSWORD MD5PASSWORD;

--Login to cacophony_metadata
\c cacophony_metadata

--Revoke all Privileges
REVOKE ALL ON DATABASE cacophony_metadata FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM PUBLIC;

--Set privileges for username
GRANT CONNECT, CREATE ON DATABASE cacophony_metadata TO USERNAME;
GRANT SELECT, INSERT, DELETE, UPDATE ON ALL TABLES IN SCHEMA public TO USERNAME;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO USERNAME;
GRANT USAGE, CREATE ON SCHEMA public to USERNAME;

--Set up default privileges for username
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, DELETE, UPDATE ON TABLES TO USERNAME;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO USERNAME;
